begin;
do $$
declare u uuid:=gen_random_uuid(); a uuid:=gen_random_uuid(); sid uuid; job jsonb; token uuid; d date:=(now() at time zone 'Asia/Tokyo')::date;
begin
 insert into auth.users(id,aud,role) values(u,'authenticated','authenticated'),(a,'authenticated','authenticated');
 insert into public.admin_users(user_id,role,is_active) values(a,'admin',true);
 perform set_config('request.jwt.claim.sub',u::text,true);
 insert into storage.objects(bucket_id,name) values('aed-submission-images',u::text||'/ai-test.jpg');
 insert into public.aed_submissions(user_id,facility_name,installation_location,address,prefecture,latitude,longitude,gps_accuracy_m,photo_object_path,photo_sha256,photo_width,photo_height,submitter_photo_license_accepted,privacy_confirmed,terms_version)
 values(u,'検証施設','入口','東京都検証住所','東京都',35.68,139.76,10,u::text||'/ai-test.jpg',repeat('a',64),640,480,true,true,'ai-rollback-test') returning id into sid;
 set local role authenticated;
 begin perform public.reserve_aed_image_check(sid,a); raise exception 'FAIL client reservation';
 exception when insufficient_privilege then null; end;
 begin insert into public.aed_image_checks(submission_id,status,request_id) values(sid,'completed',gen_random_uuid()); raise exception 'FAIL fake result';
 exception when insufficient_privilege then null; end;
 reset role;
 insert into app_private.aed_ai_daily_usage(day,attempts) values(d,0) on conflict(day) do update set attempts=0;
 set local role service_role;
 job:=public.reserve_aed_image_check(sid,a); token:=(job->>'request_id')::uuid;
 if token is null then raise exception 'FAIL reservation'; end if;
 begin perform public.reserve_aed_image_check(sid,a); raise exception 'FAIL duplicate execution';
 exception when raise_exception then if sqlerrm<>'ai_retry_later' then raise; end if; end;
 reset role;
 set local role authenticated;
 if (select count(*) from public.aed_image_checks where submission_id=sid)<>0 then raise exception 'FAIL nonadmin read'; end if;
 reset role;
 perform set_config('request.jwt.claim.sub',a::text,true);
 set local role authenticated;
 if (select count(*) from public.aed_image_checks where submission_id=sid)<>1 then raise exception 'FAIL admin read'; end if;
 reset role;
 update public.aed_image_checks set status='completed',result='{"aed":"uncertain"}' where submission_id=sid;
 set local role service_role;
 job:=public.reserve_aed_image_check(sid,a);
 if not (job->>'cached')::boolean then raise exception 'FAIL cached'; end if;
 reset role;
 if (select attempts from app_private.aed_ai_daily_usage where day=d)<>1 then raise exception 'FAIL duplicate budget'; end if;
 update public.aed_image_checks set status='failed',updated_at=now()-interval '3 minutes' where submission_id=sid;
 update app_private.aed_ai_daily_usage set attempts=100 where day=d;
 set local role service_role;
 begin perform public.reserve_aed_image_check(sid,a); raise exception 'FAIL budget';
 exception when raise_exception then if sqlerrm<>'ai_daily_limit' then raise; end if; end;
 reset role;
 if (select status from public.aed_submissions where id=sid) not in ('pending','needs_review') then raise exception 'FAIL moderation changed'; end if;
 if exists(select 1 from public.point_transactions where user_id=u) then raise exception 'FAIL points changed'; end if;
 delete from public.aed_submissions where id=sid;
 if exists(select 1 from public.aed_image_checks where submission_id=sid) then raise exception 'FAIL cascade'; end if;
end $$;
select 'PASS: service-only reservation, forged result denied, admin-only read, retry lock, cache, daily cap, moderation and points unchanged, cascade deletion. Rollback fixtures.' as result;
rollback;
