import assert from 'node:assert/strict';
import { analyzeImage, validateResult } from '../supabase/functions/aed-image-check/analyze.mjs';
import '../aed-image-ai.js';
const result = { aed: 'likely', faces: 'likely', plates: 'not_visible', quality: 'usable', regions: [{ kind: 'face', x: .1, y: .2, width: .2, height: .3 }] };
assert.equal(validateResult(result).human_review_required, true);
assert.throws(() => validateResult({ ...result, aed: 'approved' }));
assert.throws(() => validateResult({ ...result, regions: [{ ...result.regions[0], x: -.1 }] }));
assert.throws(() => validateResult({ ...result, regions: [{ ...result.regions[0], width: 2 }] }));
assert.throws(() => validateResult({ ...result, regions: [{ ...result.regions[0], height: NaN }] }));
let sent;
const jpeg = new Uint8Array([255, 216, 255, 0]);
const checked = await analyzeImage(jpeg, 'fake-test-key', async (url, options) => {
    sent = JSON.parse(options.body);
    assert.equal(url, 'https://api.openai.com/v1/responses');
    return { ok: true, json: async () => ({ status: 'completed', output: [{ content: [{ type: 'output_text', text: JSON.stringify(result) }] }] }) };
});
assert.equal(sent.store, false);
assert.equal(sent.text.format.strict, true);
assert.ok(sent.input[0].content[1].image_url.startsWith('data:image/jpeg;base64,'));
assert.equal(checked.aed, 'likely');
await assert.rejects(analyzeImage(new Uint8Array([1, 2, 3]), 'fake', () => { throw new Error('must not send'); }), /invalid_image/);
await assert.rejects(analyzeImage(jpeg, 'fake', async () => ({ ok: false, status: 429 })), /ai_rate_limited/);
await assert.rejects(analyzeImage(jpeg, 'fake', async () => ({ ok: true, json: async () => ({ status: 'incomplete' }) })), /ai_incomplete/);
await assert.rejects(analyzeImage(jpeg, 'fake', async () => ({ ok: true, json: async () => ({ status: 'completed', output: [{ content: [{ type: 'refusal' }] }] }) })), /ai_unavailable/);
const bounds = globalThis.MachimamoAedImageAI.bounds;
assert.deepEqual(bounds({ x: 0, y: 0, width: 1, height: 1 }, 100, 100), { x: 0, y: 0, width: 100, height: 100 });
const box = bounds(result.regions[0], 1000, 1000);
assert.ok(box.x <= 100 && box.y <= 200 && box.x + box.width >= 300 && box.y + box.height >= 500, 'mask expands detection');
assert.throws(() => bounds({ x: .9, y: 0, width: .5, height: .1 }, 100, 100));
console.log('PASS: provider contract, structured parsing, refusal/failure handling, image limit/signature, padded mask bounds. No live AI request made.');
