import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; create function public.admin_validate(text) returns void language plpgsql as $$begin if auth.uid() is null then raise exception 'authentication_required' using errcode='28000'; end if; if $1 <> 'test-only' then raise exception 'admin_required' using errcode='42501'; end if; end$$; create table public.admin_audit_log(id bigint generated always as identity,action text,target_type text,target_id text,detail jsonb,created_at timestamptz default now(),actor_user_id uuid);`);
await db.exec(readFileSync(new URL('../supabase/migrations/20260927150000_asp_runtime_master.sql', import.meta.url),'utf8'));
console.log('PASS migration syntax and dependency signatures');
const q=async(sql,args=[]) => (await db.query(sql,args)).rows;
const offer={offer_id:'fixture_1',asp:'fixture',program_id:'fixture',advertiser_name:'TEST ONLY',offer_name:'TEST ONLY',approval_status:'approved',services:{machimamo:{source_listing_allowed:true,source_media_approved:true,production_listing_approved:true,web_approval_status:'approved',tracking_url:'https://example.invalid/ad',point_reward_allowed:false}}};
await assert.rejects(q('select admin_import_asp_runtime($1,now(),$2::jsonb)',['test-only',JSON.stringify([offer])]),/authentication_required/);
await db.exec(`insert into auth.users values ('00000000-0000-4000-8000-000000000001'); set request.jwt.claim.sub='00000000-0000-4000-8000-000000000001';`);
await q('select admin_import_asp_runtime($1,now(),$2::jsonb)',['test-only',JSON.stringify([offer])]);
await q('select admin_import_asp_runtime($1,now(),$2::jsonb)',['test-only',JSON.stringify([offer])]);
assert.equal((await q('select count(*)::int n from asp_runtime_offers'))[0].n,1);
assert.equal((await q("select * from get_asp_offers_for_placement('machimamo','mypage')")).length,0);
await q("select admin_set_asp_publication('test-only','fixture_1','machimamo','active',true,$1::jsonb)",[JSON.stringify([{placement_id:'mypage',enabled:true}])]);
assert.equal((await q("select * from get_asp_offers_for_placement('machimamo','mypage')")).length,1);
assert.equal((await q("select * from get_asp_offers_for_placement('machiibe','mypage')")).length,0);
await q("select record_asp_offer_click('fixture_1','machimamo','mypage','test')");
await q("select * from admin_list_asp_runtime('test-only')");
await q("select admin_set_asp_publication('test-only','fixture_1','machimamo','paused',false,'[]')");
assert.equal((await q("select * from get_asp_offers_for_placement('machimamo','mypage')")).length,0);
assert.equal((await q('select count(*)::int n from asp_runtime_clicks'))[0].n,1);
const permissions=await q(`select c.relname,c.relrowsecurity,has_table_privilege('anon',c.oid,'SELECT') a,has_table_privilege('authenticated',c.oid,'INSERT') i from pg_class c where c.relname in ('asp_runtime_offers','asp_runtime_service_offers','asp_runtime_placements','asp_runtime_clicks')`);
assert.equal(permissions.length,4); assert(permissions.every(x=>x.relrowsecurity&&!x.a&&!x.i));
console.log('PASS auth rejection, idempotent import, draft gate, media separation, publish/pause, click history, admin RPC, RLS and grants');
await db.exec(`delete from auth.users where id='00000000-0000-4000-8000-000000000001'`);
assert.equal((await q('select user_id from asp_runtime_clicks'))[0].user_id,null);
console.log('PASS account deletion preserves anonymized history');
await db.close();
