const assert=require('node:assert/strict'),fs=require('node:fs');
const js=fs.readFileSync('camera-safe-ui.js','utf8'),css=fs.readFileSync('camera-safe-ui.css','utf8'),loader=fs.readFileSync('mypage-guide.js','utf8');
assert.match(js,/MachimamoCameraGuide\?\.open\(\)/,'Q&A is wired through a safe explicit click handler');
assert.match(js,/notice\.hidden=false/,'the startup notice is restored on each camera launch');
assert.match(js,/検知台数 \$\{count\}台/,'a compact cumulative detection count is available');
assert.match(js,/setDetectorState/,'the UI exposes a real detector lifecycle state');
assert.match(css,/data-state="running"/,'the detector status dot has a running state');
assert.match(css,/data-state="error"/,'the detector status dot has an error state');
assert.match(js,/slice\(0,heat==='strong'\?1:heat==='medium'\?2:3\)/,'scope count is capped and reduced under heat throttling');
assert.match(css,/body\.camera-running \.ad-banner/,'the PR strip is hidden while the camera is running');
assert.match(css,/body\.camera-running #app > header/,'the page header is hidden while the full-screen camera is running');
assert.match(css,/body\.camera-running #bottomNav/,'bottom navigation is hidden while the camera is running');
assert.match(css,/\.camera-view\.active[\s\S]*position:fixed/,'the camera uses the full viewport instead of the header-offset map area');
assert.match(js,/video\.insertAdjacentElement\('afterend',layer\)/,'the scope layer is painted after the Safari video layer');
assert.match(css,/\.camera-view \.ai-status[\s\S]*clip-path:inset\(50%\)/,'verbose live status remains accessible but is visually hidden');
assert.match(loader,/camera-safe-ui\.js\?v=42-safari-nav4/,'the camera safety layer is loaded by the deployed compatibility entrypoint');
console.log('PASS: distraction-reduced camera UI, Q&A wiring, startup notice, and scope overlay loader.');
