const assert=require('node:assert/strict'),fs=require('node:fs');
const js=fs.readFileSync('camera-safe-ui.js','utf8'),css=fs.readFileSync('camera-safe-ui.css','utf8'),loader=fs.readFileSync('mypage-guide.js','utf8');
assert.match(js,/MachimamoCameraGuide\?\.open\(\)/,'Q&A is wired through a safe explicit click handler');
assert.match(js,/notice\.hidden=false/,'the startup notice is restored on each camera launch');
assert.match(js,/検知台数 \$\{count\}台/,'a compact cumulative detection count is available');
assert.match(js,/slice\(0,heat==='strong'\?1:heat==='medium'\?2:3\)/,'scope count is capped and reduced under heat throttling');
assert.match(css,/body\.camera-running \.ad-banner/,'the PR strip is hidden while the camera is running');
assert.match(css,/body\.camera-running #app > nav/,'bottom navigation is hidden while the camera is running');
assert.match(css,/\.camera-view \.ai-status[\s\S]*clip-path:inset\(50%\)/,'verbose live status remains accessible but is visually hidden');
assert.match(loader,/camera-safe-ui\.js\?v=29-safety2/,'the camera safety layer is loaded by the deployed compatibility entrypoint');
console.log('PASS: distraction-reduced camera UI, Q&A wiring, startup notice, and scope overlay loader.');
