import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {createRequire} from 'node:module';
import {buildTokyoFocusStatic} from '../scripts/build_tokyo_focus_static_snapshot.mjs';
import {buildCompactStationSnapshot,parseWindows} from '../scripts/build_tokyo_speed_focus_station_snapshot.mjs';
const require=createRequire(import.meta.url),zones=require('../drive-beta/enforcement-zones.js');
const read=p=>fs.readFileSync(p,'utf8'),R=p=>JSON.parse(read(p)),H=p=>crypto.createHash('sha256').update(read(p).replaceAll('\r\n','\n')).digest('hex');
const sourcePath='data/drive/tokyo-focus-locations-source-v1.json',overlayPath='drive-beta/data/tokyo-focus-locations-wangan-preview-v1.json';
const source=R(sourcePath),overlay=R(overlayPath),actual=R('drive-beta/data/tokyo-focus-locations-all-v1.json');
const rebuilt=buildTokyoFocusStatic(source,overlay,{sourceSha256:H(sourcePath),overlaySha256:H(overlayPath)});
assert.deepEqual(actual,rebuilt);assert.equal(actual.events.length,214);
assert.equal(actual.events.filter(e=>e.coordinateVerified&&!e.locationApproximate).length,6);
assert.equal(actual.events.filter(e=>!e.coordinateVerified&&e.locationApproximate).length,208);
const missing=structuredClone(source);missing.events.pop();assert.throws(()=>buildTokyoFocusStatic(missing,overlay),/incomplete/);
const unrelated=structuredClone(overlay);unrelated.events[0].placeName='unmatched';assert.throws(()=>buildTokyoFocusStatic(source,unrelated),/invalid_focus_overlay/);
const duplicate=structuredClone(source);duplicate.events[1]=duplicate.events[0];assert.throws(()=>buildTokyoFocusStatic(duplicate,overlay),/invalid_focus_base/);
const stationSource=R('data/drive/tokyo-speed-focus-stations-source-v1.json'),stations=R('drive-beta/data/tokyo-speed-focus-stations-preview-v1.json');
assert.deepEqual(buildCompactStationSnapshot(stationSource),stations);
assert.equal(stations.count,97);assert(stations.data.every(row=>row.length===6));assert.equal(stations.audit.markerLocation,'POLICE_STATION_HQ_SUMMARY_NOT_ENFORCEMENT_POINT');
assert.equal(stations.audit.sourceProvenance.rawPdfArchiveAvailable,false,'Do not invent raw PDF provenance for legacy facts');
assert.equal(stations.audit.records.length,97);assert.equal(stations.audit.pdfParserVersion,'1.1.1');
const badStation=structuredClone(stationSource);badStation.events[0].windows=[[25,30]];assert.throws(()=>buildCompactStationSnapshot(badStation),/invalid_station_windows/);
assert.deepEqual(parseWindows('重点時間帯\n国道 7－18\n県道 22－6\n国道 7－18\n※注意'),[[7,18],[22,6]]);
assert.equal(require('pdf-parse/package.json').version,'1.1.1');
const current=zones.normalizeSnapshot(R('drive-beta/data/tokyo-wangan-preview-v1.json'));assert.equal(current.length,10);
assert(current.every(z=>zones.verifiedStaticGeometry(z)===null),'All ten unverified zones must be excluded from lines and alerts');
const valid={geometryVerified:true,endpointVerified:true,geometryStatus:'VERIFIED',freshnessStatus:'CURRENT',staticGeometry:[[35,139],[35.1,139.1]]};assert.deepEqual(zones.verifiedStaticGeometry(valid),valid.staticGeometry);
for(const override of [{geometryVerified:false},{endpointVerified:false},{geometryStatus:'ENDPOINTS_CROSSCHECKED'},{freshnessStatus:'STALE'},{staticGeometry:[[NaN,139],[35,139]]},{staticGeometry:null}])assert.equal(zones.verifiedStaticGeometry({...valid,...override}),null);
const app=read('drive-beta/app.js'),html=read('drive-beta/index.html');
assert.doesNotMatch(app,/router\.project-osrm\.org|\/api\/drive-focus-tokyo|japanese-addresses-v2\.geoloniamaps/);
assert.match(app,/https:\/\/tile\.openstreetmap\.org\/\{z\}\/\{x\}\/\{y\}\.png/);
assert.match(app,/openstreetmap\.org\/copyright/);
assert.match(html,/@supabase\/supabase-js@2\.117\.2"/);assert.match(html,/leaflet@1\.9\.4/);
assert.match(html,/表示中の地図範囲を取得に使用/);
assert.match(app,/persistSession:false,autoRefreshToken:false/);assert.match(app,/accidentVisible=false/);assert.match(app,/accident_hotspots_in_view/);
assert.match(app,/filter\(z=>zonesApi\.verifiedStaticGeometry\(z\)&&resolvedGeometries\.has/);
assert.equal((html.match(/role="tab"/g)||[]).length,2);
console.log('PASS: offline static214/6/208, compact97/audit, incomplete-source rejection, static Geometry fail-closed, CDN/accident contracts');
