'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const script = fs.readFileSync(path.join(__dirname, '..', 'news-publishing-admin.js'), 'utf8');
const adapter = fs.readFileSync(path.join(__dirname, '..', 'news-candidate-adapter.js'), 'utf8');
const detail = fs.readFileSync(path.join(__dirname, '..', 'news-candidate-detail.js'), 'utf8');
const qaFixtures = require('../news-canonical-qa-fixture.js');
assert.match(html, /id="adminNewsPublishingSection"/);
assert.match(html, /news-candidate-adapter\.js\?v=2-detail/);
assert.match(html, /news-candidate-detail\.js\?v=1/);
assert.match(html, /news-canonical-qa-fixture\.js\?v=1/);
assert.match(html, /news-publishing-admin\.js\?v=4-readonly-detail-fixture/);
assert.ok(html.indexOf('news-candidate-adapter.js?v=2-detail') < html.indexOf('news-candidate-detail.js?v=1'));
assert.ok(html.indexOf('news-candidate-detail.js?v=1') < html.indexOf('news-canonical-qa-fixture.js?v=1'));
assert.ok(html.indexOf('news-canonical-qa-fixture.js?v=1') < html.indexOf('news-publishing-admin.js?v=4-readonly-detail-fixture'));
assert.match(html, /単体ニュース \/ TikTok SHORT・SINGLE（43秒）/);
assert.match(html, /ウィークリー投稿 \/ TikTok LONG・WEEKLY（CURRENT尺）/);
assert.match(html, /id="adminSocialPostArea"/);
assert.ok(html.indexOf('id="adminNewsPublishingSection"') < html.indexOf('SNS投稿素材（直近の公開投稿）'));
assert.match(html, /id="adminWeeklyWeek" type="week" required/);
assert.match(html, /id="adminWeeklyPrefecture" required/);
assert.match(html, /<option value="12">12件<\/option>/);
assert.match(html, /id="adminNewsShowPosted" type="checkbox"/);
assert.match(html, /Xへ投稿（接続設定必要）/);
assert.match(html, /TikTokへ投稿（接続設定必要）/);
assert.match(html, /id="adminNewsDetailModal"/);
assert.match(html, /id="adminNewsDetailBody"/);
assert.match(html, /news-detail-sheet/);
assert.match(html, /body\.news-detail-open \.ad-banner \{ display:none !important;/);
assert.match(html, /env\(safe-area-inset-top\)/);
assert.match(html, /env\(safe-area-inset-bottom\)/);
assert.match(html, /word-break:break-all/);
assert.match(html, /body\.admin-dashboard-open \.ad-banner \{ display: none !important;/);
assert.match(html, /NEWS_ADMIN_QA_PREVIEW_HOST = 'machimamo-map-git-feat-dev34-current-production-engine-miti4\\.vercel\\.app'/);
assert.match(html, /params\\.get\\('newsAdminQa'\\) === '1'/);
assert.match(html, /admin-news-qa-only/);
assert.match(html, /Preview QA・閲覧専用/);
assert.match(html, /if \\(openNewsAdminPreviewQa\\(\\)\\)/);

assert.match(script, /const SERVICE_ID = 'machimamo'/);
assert.match(script, /serviceId: SERVICE_ID/);
assert.match(script, /'地域の異変|LOCAL_ANOMALY/);
assert.match(script, /'POLICE_OFFICIAL'/);
assert.match(script, /prefectureCount: PREFECTURES.length/);
assert.match(script, /candidateSource: 'public\.spots:official\(read-only,legacy-unverified\)'/);
assert.match(script, /connected: 'read-only-legacy'/);
assert.match(script, /LEGACY_UNVERIFIED/);
assert.match(script, /db\.from\('spots'\)/);
assert.match(script, /\.select\('id,created_at,category,title,comment,address,is_hidden,report_count'\)/);
assert.match(script, /Production候補/);
assert.match(script, /canonical dry-run fixture/);
assert.match(script, /MachimamoCanonicalQaFixtures/);
assert.match(script, /data-news-detail-id/);
assert.match(script, /openCandidateDetail/);
assert.match(script, /bindCandidateDetailNavigation/);
assert.match(script, /MachimamoNewsCandidateDetail/);
assert.match(adapter, /publishEligible: false/);
assert.match(adapter, /rightsStatus: 'needs_review'/);
assert.match(adapter, /legacyComment:/);
assert.match(adapter, /legacyAddress:/);
assert.match(detail, /旧ニュース候補・要確認/);
assert.match(detail, /Productionへ進める候補/);
assert.match(detail, /Renderer待ち（exact v7 source）/);
assert.match(detail, /publishEligible/);
assert.match(detail, /rightsScopeConfirmed/);
assert.match(script, /MutationObserver/);

const prefectures = [...script.matchAll(/'([^']+[都道府県])'/g)].map((match) => match[1]);
assert.equal(prefectures.length, 47);
assert.equal(new Set(prefectures).size, 47);
process.stdout.write('news publishing admin UI contract: PASS (read-only detail, legacy/canonical gates, mobile QA, service scope)\n');

assert.equal(qaFixtures.length, 3);
assert.ok(qaFixtures.every(x => x.fixtureOnly === true));
assert.ok(qaFixtures.every(x => x.informationKind === 'POLICE_OFFICIAL'));
assert.ok(qaFixtures.every(x => x.productionEligible === true));
assert.ok(qaFixtures.every(x => /^[0-9a-f]{64}$/.test(x.source.sourceHash)));
