-- Run inside BEGIN/ROLLBACK. UUID fixtures only; never calls Storage/Auth APIs.
do $$
declare u uuid:=gen_random_uuid(); other_u uuid:=gen_random_uuid(); a uuid:=gen_random_uuid(); req uuid:=gen_random_uuid();
 p jsonb:='{"lat":35.68,"lng":139.76,"category":"danger","title":"開発26検証","comment":"rollback only","address":"test","source":"camera","origin_lat":35.68,"origin_lng":139.76,"image_url":null}';
 r jsonb;r2 jsonb;e uuid;ep text;b jsonb;tok uuid;job uuid;rid bigint;i integer;
begin
 insert into auth.users(id,aud,role) values(u,'authenticated','authenticated'),(other_u,'authenticated','authenticated'),(a,'authenticated','authenticated');
 insert into public.profiles(auth_id,name,point) values(u,'dev26 fixture',0),(other_u,'dev26 other',0);
 insert into public.admin_users(user_id,role,is_active) values(a,'admin',true);
 perform set_config('request.jwt.claim.sub',u::text,true);set local role authenticated;
 r:=public.submit_spot_once(req,p);r2:=public.submit_spot_once(req,p);
 if r->>'id'<>r2->>'id' or r2->>'replayed'<>'true' then raise exception 'FAIL replay'; end if;
 if (select count(*) from public.point_transactions where user_id=u)<>1 then raise exception 'FAIL reward replay'; end if;
 begin perform public.submit_spot_once(req,p||'{"title":"changed"}');raise exception 'FAIL changed payload accepted';exception when raise_exception then if sqlerrm<>'request_payload_mismatch' then raise;end if;end;
 begin perform public.submit_spot_once(gen_random_uuid(),p||'{"lat":35.69}');raise exception 'FAIL radius';exception when raise_exception then if sqlerrm<>'camera_location_outside_50m' then raise;end if;end;
 begin perform public.submit_spot_once(gen_random_uuid(),p||'{"image_url":"https://example.com/raw.jpg"}');raise exception 'FAIL camera image public';exception when raise_exception then if sqlerrm<>'invalid_camera_post' then raise;end if;end;
 begin insert into public.spots(lat,lng,title,category,created_by) values(35,139,'bypass','danger',u);raise exception 'FAIL direct insert';exception when insufficient_privilege then null;end;
 for i in 1..6 loop r2:=public.submit_spot_once(gen_random_uuid(),p);end loop;
 if (select sum(amount) from public.point_transactions where user_id=u and reason='spot_post')<>50 or (r2->>'awarded')::int<>0 then raise exception 'FAIL daily cap';end if;
 r:=public.prepare_camera_evidence_once((r->>'id')::bigint,req);e:=(r->>'id')::uuid;ep:=r->>'object_path';
 r2:=public.prepare_camera_evidence_once((select spot_id from public.camera_evidence where id=e),req);
 if r2->>'id'<>e::text then raise exception 'FAIL evidence replay';end if;
 perform set_config('request.jwt.claim.sub',other_u::text,true);
 if exists(select 1 from public.camera_evidence where id=e) then raise exception 'FAIL foreign evidence read';end if;
 begin perform public.finalize_camera_evidence(e,repeat('a',64),640,480,true);raise exception 'FAIL foreign finalize';exception when raise_exception then if sqlerrm<>'evidence_not_found' then raise;end if;end;
 begin perform public.request_my_camera_evidence_deletion(e);raise exception 'FAIL foreign delete';exception when raise_exception then if sqlerrm<>'evidence_not_found' then raise;end if;end;
 begin perform public.admin_camera_evidence('invalid','list','{}');raise exception 'FAIL nonadmin';exception when insufficient_privilege then null;end;
 begin perform public.camera_evidence_cleanup_batch(50);raise exception 'FAIL client cleanup';exception when insufficient_privilege then null;end;
 reset role;
 insert into storage.objects(bucket_id,name,owner_id,metadata) values('camera-evidence',ep,u::text,'{"size":1000,"mimetype":"image/jpeg"}');
 perform set_config('request.jwt.claim.sub',u::text,true);set local role authenticated;
 perform public.finalize_camera_evidence(e,repeat('a',64),640,480,true);
 perform public.finalize_camera_evidence(e,repeat('a',64),640,480,true);
 if (select normal_delete_at-finalized_at from public.camera_evidence where id=e)<>interval '10 days' then raise exception 'FAIL ten days';end if;
 reset role;
 if (select count(*) from app_private.camera_evidence_audit where evidence_id=e and action='finalized')<>1 then raise exception 'FAIL double finalized';end if;
 insert into public.user_moderation(user_id,status,reason) values(u,'suspended','test');
 perform set_config('request.jwt.claim.sub',u::text,true);set local role authenticated;
 begin perform public.finalize_camera_evidence(e,repeat('a',64),640,480,true);raise exception 'FAIL suspended finalize';exception when insufficient_privilege then null;end;
 begin perform public.submit_spot_once(req,p);raise exception 'FAIL suspended replay';exception when insufficient_privilege then null;end;
 reset role;
 perform set_config('request.jwt.claim.sub',a::text,true);
 begin perform app_private.camera_evidence_admin_operation('preserve',jsonb_build_object('id',e,'reason','short'));raise exception 'FAIL missing reason';exception when raise_exception then if sqlerrm<>'preserve_reason_required' then raise;end if;end;
 perform app_private.camera_evidence_admin_operation('preserve',jsonb_build_object('id',e,'reason','isolated test preservation reason'));
 if (select preserve_until from public.camera_evidence where id=e)<>now()+interval '30 days' then raise exception 'FAIL preservation 30d';end if;
 update public.camera_evidence set preserve_until=now()-interval '2 days' where id=e;
 update app_private.camera_cleanup_control set last_started_at=null where task='retention';b:=public.camera_evidence_cleanup_batch(100);
 if (select decision_due_at from public.camera_evidence where id=e)<>now()+interval '5 days' then raise exception 'FAIL grace anchored to expiry';end if;
 perform app_private.camera_evidence_admin_operation('extend',jsonb_build_object('id',e,'reason','isolated test extension reason'));
 if (select preserve_until from public.camera_evidence where id=e)<>now()+interval '30 days' then raise exception 'FAIL extension';end if;
 update public.camera_evidence set preserve_until=now()-interval '8 days' where id=e;
 update app_private.camera_cleanup_control set last_started_at=null where task='retention';b:=public.camera_evidence_cleanup_batch(100);tok:=(b->>'token')::uuid;
 if (select state from public.camera_evidence where id=e)<>'delete_queued' then raise exception 'FAIL expired grace';end if;
 perform public.camera_evidence_cleanup_result(e,tok,false,'storage_delete_failed');
 update app_private.camera_cleanup_control set last_started_at=null where task='retention';b:=public.camera_evidence_cleanup_batch(100);tok:=(b->>'token')::uuid;
 begin perform public.camera_evidence_cleanup_result(e,gen_random_uuid(),true,null);raise exception 'FAIL stale token';exception when raise_exception then if sqlerrm<>'cleanup_claim_invalid' then raise;end if;end;
 perform public.camera_evidence_cleanup_result(e,tok,true,null);
 if exists(select 1 from public.camera_evidence where id=e and (user_id is not null or sha256 is not null or object_path is not null)) then raise exception 'FAIL scrub';end if;
 if exists(select 1 from app_private.camera_evidence_audit where evidence_id=e and actor_id is not null) then raise exception 'FAIL deleted audit identity';end if;
 -- A separate no-object account verifies DB cleanup without touching any real storage.
 perform set_config('request.jwt.claim.sub',other_u::text,true);r:=public.prepare_camera_evidence_once(null,gen_random_uuid());e:=(r->>'id')::uuid;
 insert into public.account_deletion_requests(user_id,status) values(other_u,'processing') returning id into rid;
 insert into public.account_deletion_jobs(user_id,request_id,started_by) values(other_u,rid,a) returning id into job;
 perform app_private.account_deletion_clean_data(job);perform app_private.account_deletion_clean_data(job);
 if exists(select 1 from public.camera_evidence where id=e and (user_id is not null or object_path is not null or state<>'deleted')) then raise exception 'FAIL account camera scrub';end if;
 if exists(select 1 from app_private.camera_evidence_audit where actor_id=other_u) then raise exception 'FAIL audit scrub';end if;
 insert into public.user_moderation(user_id,status,reason) values(a,'suspended','test');
 perform set_config('request.jwt.claim.sub',a::text,true);set local role authenticated;
 if public.is_current_user_admin() then raise exception 'FAIL suspended admin';end if;
 perform set_config('request.jwt.claim.sub','',true);set local role anon;
 begin perform public.submit_spot_once(req,p);raise exception 'FAIL anonymous post';exception when insufficient_privilege then null;end;
 begin perform public.prepare_camera_evidence_once(null,req);raise exception 'FAIL anonymous photo';exception when insufficient_privilege then null;end;
 reset role;
end$$;
select 'PASS dev26 replay / payload mismatch / 50m / private camera / direct insert denial / point cap / owner-other-anon-suspended / finalize replay / 10d / reason / 30d / grace anchored to expiry / extension / cleanup token / retry / account camera scrub' result;
