// Generated from the five verified production seed SQL files for Preview QA only.
// Factual fields only. No source prose, logos or event images are copied.
// Do not use this file as a Production seed, SNS source, ASP source or SEO corpus.
export const QA_VERIFIED_SEED_SNAPSHOTS=[
  {
    "id": 92001,
    "slug": "qa-seed-water-kendama-20260921",
    "title": "けん玉ショー＆ワークショップ",
    "summary": null,
    "start_date": "2026-09-21",
    "end_date": "2026-09-21",
    "start_time": null,
    "end_time": null,
    "all_day": false,
    "schedule_type": "irregular",
    "venue_name": "東京都水の科学館 1F オリエンテーションルーム",
    "postal_code": "135-0063",
    "prefecture": "東京都",
    "municipality": "江東区",
    "address": "有明3-1-8",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "culture_public"
    ],
    "price_text": "入館・館内体験は無料",
    "price_type": "free",
    "is_free": true,
    "reservation_required": false,
    "reservation_text": "各回1時間前から整理券配布・予約不可",
    "organizer_name": "東京都水の科学館",
    "official_url": "https://www.mizunokagaku.jp/event/260921_kendama_show/",
    "category_keys": [
      "family",
      "learning"
    ],
    "age_group_keys": [
      "preschool",
      "elementary",
      "family"
    ],
    "indoor": true,
    "audience_intent": "child_centered",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "東京都水の科学館",
    "source_url": "https://www.mizunokagaku.jp/event/260921_kendama_show/",
    "source_event_key": "260921_kendama_show",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "water-kendama-20260921"
  },
  {
    "id": 92002,
    "slug": "qa-seed-water-clown-rio-20260922",
    "title": "クラウン・リオのパフォーマンスショー",
    "summary": null,
    "start_date": "2026-09-22",
    "end_date": "2026-09-22",
    "start_time": null,
    "end_time": null,
    "all_day": false,
    "schedule_type": "irregular",
    "venue_name": "東京都水の科学館 1F オリエンテーションルーム",
    "postal_code": "135-0063",
    "prefecture": "東京都",
    "municipality": "江東区",
    "address": "有明3-1-8",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "culture_public"
    ],
    "price_text": "入館・館内体験は無料",
    "price_type": "free",
    "is_free": true,
    "reservation_required": false,
    "reservation_text": "各回1時間前から整理券配布・予約不可",
    "organizer_name": "東京都水の科学館",
    "official_url": "https://www.mizunokagaku.jp/event/260922_clown_rio_show/",
    "category_keys": [
      "family",
      "entertainment"
    ],
    "age_group_keys": [
      "preschool",
      "elementary",
      "family"
    ],
    "indoor": true,
    "audience_intent": "child_centered",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "東京都水の科学館",
    "source_url": "https://www.mizunokagaku.jp/event/260922_clown_rio_show/",
    "source_event_key": "260922_clown_rio_show",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "water-clown-rio-20260922"
  },
  {
    "id": 92003,
    "slug": "qa-seed-water-seoppi-20260923",
    "title": "SEOPPIのスポーツスタッキングショー",
    "summary": null,
    "start_date": "2026-09-23",
    "end_date": "2026-09-23",
    "start_time": null,
    "end_time": null,
    "all_day": false,
    "schedule_type": "irregular",
    "venue_name": "東京都水の科学館 1F オリエンテーションルーム",
    "postal_code": "135-0063",
    "prefecture": "東京都",
    "municipality": "江東区",
    "address": "有明3-1-8",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "culture_public"
    ],
    "price_text": "入館・館内体験は無料",
    "price_type": "free",
    "is_free": true,
    "reservation_required": false,
    "reservation_text": "各回1時間前から整理券配布・予約不可",
    "organizer_name": "東京都水の科学館",
    "official_url": "https://www.mizunokagaku.jp/event/260923_seoppi_show/",
    "category_keys": [
      "family",
      "sports"
    ],
    "age_group_keys": [
      "preschool",
      "elementary",
      "family"
    ],
    "indoor": true,
    "audience_intent": "child_centered",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "東京都水の科学館",
    "source_url": "https://www.mizunokagaku.jp/event/260923_seoppi_show/",
    "source_event_key": "260923_seoppi_show",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "water-seoppi-20260923"
  },
  {
    "id": 92004,
    "slug": "qa-seed-miraikan-moon-2026",
    "title": "中秋の名月 未来館でお月見！2026",
    "summary": null,
    "start_date": "2026-09-18",
    "end_date": "2026-09-27",
    "start_time": null,
    "end_time": null,
    "all_day": false,
    "schedule_type": "recurring",
    "venue_name": "日本科学未来館",
    "postal_code": "135-0064",
    "prefecture": "東京都",
    "municipality": "江東区",
    "address": "青海2-3-6",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "culture_public"
    ],
    "price_text": "参加費は入館料のみ",
    "price_type": "paid",
    "is_free": false,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "日本科学未来館",
    "official_url": "https://www.miraikan.jst.go.jp/events/202609184720.html",
    "category_keys": [
      "learning",
      "nature"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [
      "captions"
    ],
    "accessibility_notes": "字幕が必要な場合は事前相談。手話通訳は9月22日の13:35プログラムのみ。",
    "fandom_slugs": [],
    "source_name": "日本科学未来館",
    "source_url": "https://www.miraikan.jst.go.jp/events/202609184720.html",
    "source_event_key": "202609184720",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "miraikan-moon-2026"
  },
  {
    "id": 92005,
    "slug": "qa-seed-city-circuit-kart-ev-20260923",
    "title": "AUTOBACS 全日本カート選手権 EV部門 第5戦・第6戦／キッズEVカート無料走行体験",
    "summary": null,
    "start_date": "2026-09-23",
    "end_date": "2026-09-23",
    "start_time": "10:00",
    "end_time": "18:50",
    "all_day": false,
    "schedule_type": "single",
    "venue_name": "CITY CIRCUIT TOKYO BAY",
    "postal_code": "135-0064",
    "prefecture": "東京都",
    "municipality": "江東区",
    "address": "青海1丁目3-12",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "amusement"
    ],
    "price_text": "レース観戦とキッズEVカートは無料。電動バイク体験は1,000円",
    "price_type": "partly_free",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": "キッズEVカートは事前予約なし",
    "organizer_name": "CITY CIRCUIT TOKYO BAY",
    "official_url": "https://city-circuit.com/2026/09/alljapankartingchampionship_ev_263/",
    "category_keys": [
      "family",
      "sports"
    ],
    "age_group_keys": [
      "family"
    ],
    "indoor": null,
    "audience_intent": "family_friendly",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "CITY CIRCUIT TOKYO BAY",
    "source_url": "https://city-circuit.com/2026/09/alljapankartingchampionship_ev_263/",
    "source_event_key": "alljapankartingchampionship_ev_263",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "city-circuit-kart-ev-20260923"
  },
  {
    "id": 92006,
    "slug": "qa-seed-littleplanet-halloween-divercity-2026",
    "title": "リトルプラネット ハロウィン2026",
    "summary": null,
    "start_date": "2026-09-17",
    "end_date": "2026-11-01",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "リトルプラネット ダイバーシティ東京プラザ",
    "postal_code": null,
    "prefecture": "東京都",
    "municipality": "江東区",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "mall",
      "amusement"
    ],
    "price_text": "パーク入場料が必要（料金は公式サイト参照）",
    "price_type": "paid",
    "is_free": false,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "リトルプラネット",
    "official_url": "https://www.litpla.com/news/press/halloween2026-info/",
    "category_keys": [
      "family",
      "entertainment"
    ],
    "age_group_keys": [
      "family"
    ],
    "indoor": true,
    "audience_intent": "family_friendly",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "リトルプラネット",
    "source_url": "https://www.litpla.com/news/press/halloween2026-info/",
    "source_event_key": "halloween2026-info-divercity",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "littleplanet-halloween-divercity-2026"
  },
  {
    "id": 92007,
    "slug": "qa-seed-ariake-quizknock-nazotoki-2026",
    "title": "有明ガーデン周遊謎解き「神の使いと叶えられない願い事」",
    "summary": null,
    "start_date": "2026-08-29",
    "end_date": "2026-10-04",
    "start_time": "10:00",
    "end_time": "21:00",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "有明ガーデン各所",
    "postal_code": null,
    "prefecture": "東京都",
    "municipality": "江東区",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "mall"
    ],
    "price_text": "販売価格2,500円（税込）",
    "price_type": "paid",
    "is_free": false,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "有明ガーデン",
    "official_url": "https://ariake.shopping-sumitomo-rd.com/event/3843/",
    "category_keys": [
      "learning",
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": null,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [
      "quizknock"
    ],
    "source_name": "有明ガーデン",
    "source_url": "https://ariake.shopping-sumitomo-rd.com/event/3843/",
    "source_event_key": "3843",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "ariake-quizknock-nazotoki-2026"
  },
  {
    "id": 92008,
    "slug": "qa-seed-joypolis-sidem-3-2026",
    "title": "アイドルマスター SideM in JOYPOLIS 3",
    "summary": null,
    "start_date": "2026-09-12",
    "end_date": "2026-12-06",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "東京ジョイポリス",
    "postal_code": "135-0091",
    "prefecture": "東京都",
    "municipality": "港区",
    "address": "台場1丁目6番1号 DECKS Tokyo Beach 3F～5F",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "amusement"
    ],
    "price_text": "スペシャルショーは無料。東京ジョイポリス入場料が必要で、ほか有料コンテンツあり",
    "price_type": "partly_free",
    "is_free": null,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "東京ジョイポリス",
    "official_url": "https://tokyo-joypolis.com/event/sidem_jp2026/index.html",
    "category_keys": [
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [
      "idolmaster-sidem"
    ],
    "source_name": "東京ジョイポリス",
    "source_url": "https://tokyo-joypolis.com/event/sidem_jp2026/index.html",
    "source_event_key": "sidem_jp2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "joypolis-sidem-3-2026"
  },
  {
    "id": 92009,
    "slug": "qa-seed-toyosu-kamimaro-202609",
    "title": "紙磨呂（かみまろ）マジックショー",
    "summary": null,
    "start_date": "2026-09-23",
    "end_date": "2026-09-30",
    "start_time": null,
    "end_time": null,
    "all_day": false,
    "schedule_type": "irregular",
    "venue_name": "豊洲 千客万来 二階 時の鐘広場",
    "postal_code": null,
    "prefecture": "東京都",
    "municipality": "江東区",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "mall"
    ],
    "price_text": "観覧無料",
    "price_type": "free",
    "is_free": true,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "豊洲 千客万来",
    "official_url": "https://www.toyosu-senkyakubanrai.jp/eventnews/0729",
    "category_keys": [
      "entertainment"
    ],
    "age_group_keys": [
      "family"
    ],
    "indoor": null,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "豊洲 千客万来",
    "source_url": "https://www.toyosu-senkyakubanrai.jp/eventnews/0729",
    "source_event_key": "0729",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "toyosu-kamimaro-202609"
  },
  {
    "id": 92010,
    "slug": "qa-seed-dainankyoku-2026",
    "title": "特別展「大南極展」",
    "summary": null,
    "start_date": "2026-07-01",
    "end_date": "2026-09-27",
    "start_time": "10:00",
    "end_time": "17:00",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "日本科学未来館 1階 企画展示ゾーン",
    "postal_code": "135-0064",
    "prefecture": "東京都",
    "municipality": "江東区",
    "address": "青海2-3-6",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "culture_public"
    ],
    "price_text": "大人2,000円／18歳以下1,300円／3歳以上未就学児900円。2歳以下無料",
    "price_type": "paid",
    "is_free": false,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": null,
    "official_url": "https://dainankyokuten.jp/",
    "category_keys": [
      "learning",
      "nature"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [
      "disability_discount",
      "companion_support"
    ],
    "accessibility_notes": "障害者手帳・受給者証等の証明書所持者は本人と付添1名まで無料。",
    "fandom_slugs": [],
    "source_name": "特別展「大南極展」公式サイト",
    "source_url": "https://dainankyokuten.jp/",
    "source_event_key": "dainankyoku-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "dainankyoku-2026"
  },
  {
    "id": 92011,
    "slug": "qa-seed-sunshine-gashapon-tours-2026",
    "title": "ガシャっと回してポーンツアーズ2026",
    "summary": null,
    "start_date": "2026-10-09",
    "end_date": "2026-10-11",
    "start_time": null,
    "end_time": null,
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "サンシャインシティ 展示ホールB",
    "postal_code": null,
    "prefecture": "東京都",
    "municipality": "豊島区",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "mall",
      "event_venue_indoor"
    ],
    "price_text": "入場無料",
    "price_type": "free",
    "is_free": true,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "株式会社バンダイ",
    "official_url": "https://sunshinecity.jp/event/entry-38626.html",
    "category_keys": [
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "サンシャインシティ",
    "source_url": "https://sunshinecity.jp/event/entry-38626.html",
    "source_event_key": "entry-38626",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "sunshine-gashapon-tours-2026"
  },
  {
    "id": 92012,
    "slug": "qa-seed-tdc-hybrid-training-2026",
    "title": "Hybrid Training in Tokyo Dome City",
    "summary": null,
    "start_date": "2026-10-19",
    "end_date": "2026-10-22",
    "start_time": null,
    "end_time": null,
    "all_day": false,
    "schedule_type": "irregular",
    "venue_name": "東京ドームシティ アトラクションズ バイキング芝生広場・スプラッシュガーデン",
    "postal_code": "112-8575",
    "prefecture": "東京都",
    "municipality": "文京区",
    "address": "後楽1-3-61",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "amusement",
      "event_venue_outdoor"
    ],
    "price_text": "チケット販売予定。料金は公式情報を確認",
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "株式会社東京ドーム",
    "official_url": "https://www.tokyo-dome.co.jp/event/city/hybrid_training2026.html",
    "category_keys": [
      "sports"
    ],
    "age_group_keys": [],
    "indoor": false,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "東京ドームシティ",
    "source_url": "https://www.tokyo-dome.co.jp/event/city/hybrid_training2026.html",
    "source_event_key": "hybrid_training2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "tdc-hybrid-training-2026"
  },
  {
    "id": 92013,
    "slug": "qa-seed-tdc-toukenranbu-return-2026",
    "title": "ミュージカル『刀剣乱舞』 ～月夜一縷～ × 東京ドームシティ（東京凱旋公演期間）",
    "summary": null,
    "start_date": "2026-10-17",
    "end_date": "2026-10-25",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "東京ドームシティ",
    "postal_code": "112-8575",
    "prefecture": "東京都",
    "municipality": "文京区",
    "address": "後楽1-3-61",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "amusement"
    ],
    "price_text": "コラボフード・ドリンク等は有料。詳細は公式情報を確認",
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": null,
    "official_url": "https://www.tokyo-dome.co.jp/event/city/musical-toukenranbu_autumn2026.html",
    "category_keys": [
      "entertainment",
      "food"
    ],
    "age_group_keys": [],
    "indoor": null,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [
      "touken-ranbu"
    ],
    "source_name": "東京ドームシティ",
    "source_url": "https://www.tokyo-dome.co.jp/event/city/musical-toukenranbu_autumn2026.html",
    "source_event_key": "musical-toukenranbu-autumn2026-return",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "tdc-toukenranbu-return-2026"
  },
  {
    "id": 92014,
    "slug": "qa-seed-lalaport-jujutsu-5th-2026",
    "title": "アニメ『呪術廻戦』5周年記念！ららぽーと・ラゾーナコラボキャンペーン",
    "summary": null,
    "start_date": "2026-09-29",
    "end_date": "2026-10-14",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "ららぽーとTOKYO-BAY",
    "postal_code": null,
    "prefecture": "千葉県",
    "municipality": "船橋市",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "mall"
    ],
    "price_text": "館内企画と購入条件付き特典あり。詳細は公式情報を確認",
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": null,
    "official_url": "https://mitsui-shopping-park.com/lalaport/tokyo-bay/event/3612314.html",
    "category_keys": [
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [
      "jujutsu-kaisen"
    ],
    "source_name": "ららぽーとTOKYO-BAY",
    "source_url": "https://mitsui-shopping-park.com/lalaport/tokyo-bay/event/3612314.html",
    "source_event_key": "3612314",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "lalaport-jujutsu-5th-2026"
  },
  {
    "id": 92015,
    "slug": "qa-seed-kamogawa-beluga-50th-2026",
    "title": "ベルーガ50th Anniversary",
    "summary": null,
    "start_date": "2026-09-01",
    "end_date": "2027-06-30",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "鴨川シーワールド",
    "postal_code": null,
    "prefecture": "千葉県",
    "municipality": "鴨川市",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "amusement"
    ],
    "price_text": "入館料金等は公式料金案内を確認",
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "鴨川シーワールド",
    "official_url": "https://www.kamogawa-seaworld.jp/event/event_info/15821/",
    "category_keys": [
      "nature",
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": null,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "鴨川シーワールド",
    "source_url": "https://www.kamogawa-seaworld.jp/event/event_info/15821/",
    "source_event_key": "event-info-15821",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "kamogawa-beluga-50th-2026"
  },
  {
    "id": 92016,
    "slug": "qa-seed-metsa-harvest-2026",
    "title": "ムーミンバレーパークのハーベスト 2026",
    "summary": null,
    "start_date": "2026-09-12",
    "end_date": "2026-10-25",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "ムーミンバレーパーク",
    "postal_code": "357-0001",
    "prefecture": "埼玉県",
    "municipality": "飯能市",
    "address": "宮沢327-6",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "amusement"
    ],
    "price_text": "パーク入場料金は公式料金案内を確認",
    "price_type": "paid",
    "is_free": false,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "株式会社ムーミン物語",
    "official_url": "https://metsa-hanno.com/event/47103/",
    "category_keys": [
      "nature",
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": false,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [
      "moomin"
    ],
    "source_name": "ムーミンバレーパーク・メッツァビレッジ",
    "source_url": "https://metsa-hanno.com/event/47103/",
    "source_event_key": "event-47103",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "metsa-harvest-2026"
  },
  {
    "id": 92017,
    "slug": "qa-seed-metsa-fika-20261004",
    "title": "ムーミン谷のフィーカ2026 スノークのおじょうさん・リトルミイ",
    "summary": null,
    "start_date": "2026-10-04",
    "end_date": "2026-10-04",
    "start_time": "13:00",
    "end_time": "14:00",
    "all_day": false,
    "schedule_type": "single",
    "venue_name": "ムーミンバレーパーク KOKEMUS 2F ライブラリーカフェ",
    "postal_code": "357-0001",
    "prefecture": "埼玉県",
    "municipality": "飯能市",
    "address": "宮沢327-6",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "amusement"
    ],
    "price_text": "おとな・こども共通 1人5,000円（税込）",
    "price_type": "paid",
    "is_free": false,
    "reservation_required": true,
    "reservation_text": "予約必須・販売30席",
    "organizer_name": "株式会社ムーミン物語",
    "official_url": "https://metsa-hanno.com/event/47406/",
    "category_keys": [
      "food",
      "entertainment"
    ],
    "age_group_keys": [
      "family"
    ],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [
      "moomin"
    ],
    "source_name": "ムーミンバレーパーク・メッツァビレッジ",
    "source_url": "https://metsa-hanno.com/event/47406/",
    "source_event_key": "event-47406",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "metsa-fika-20261004"
  },
  {
    "id": 92018,
    "slug": "qa-seed-solamachi-space-brothers-2026",
    "title": "宇宙兄弟展「完結：」〜ふたつの軌跡〜",
    "summary": null,
    "start_date": "2026-09-05",
    "end_date": "2026-10-04",
    "start_time": "10:00",
    "end_time": "20:00",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "東京ソラマチ 5F スペース634",
    "postal_code": "131-0045",
    "prefecture": "東京都",
    "municipality": "墨田区",
    "address": "押上1-1-2",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "mall",
      "event_venue_indoor"
    ],
    "price_text": "入場料1,969円（税込）",
    "price_type": "paid",
    "is_free": false,
    "reservation_required": null,
    "reservation_text": "最終日は17:00終了（最終入場16:30）",
    "organizer_name": null,
    "official_url": "https://www.tokyo-solamachi.jp/autumn/event/",
    "category_keys": [
      "learning",
      "entertainment",
      "art"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "東京ソラマチ",
    "source_url": "https://www.tokyo-solamachi.jp/autumn/event/",
    "source_event_key": "space-brothers-conclusion-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "solamachi-space-brothers-2026"
  },
  {
    "id": 92019,
    "slug": "qa-seed-joypolis-halloween-2026",
    "title": "Happy Halloween JOYPOLIS 2026",
    "summary": null,
    "start_date": "2026-09-19",
    "end_date": "2026-10-31",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "東京ジョイポリス",
    "postal_code": "135-0091",
    "prefecture": "東京都",
    "municipality": "港区",
    "address": "台場1丁目6番1号 DECKS Tokyo Beach 3F～5F",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "amusement"
    ],
    "price_text": "東京ジョイポリスの入場料・パスポート等が必要。企画により別料金あり",
    "price_type": "paid",
    "is_free": false,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "東京ジョイポリス",
    "official_url": "https://tokyo-joypolis.com/event/Halloween2026/index.html",
    "category_keys": [
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "東京ジョイポリス",
    "source_url": "https://tokyo-joypolis.com/event/Halloween2026/index.html",
    "source_event_key": "Halloween2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "joypolis-halloween-2026"
  },
  {
    "id": 92020,
    "slug": "qa-seed-joypolis-hololive-shiny-party",
    "title": "ホロライブ × ジョイポリス SHINY PARTY",
    "summary": null,
    "start_date": "2026-10-16",
    "end_date": "2026-12-27",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "東京ジョイポリス",
    "postal_code": "135-0091",
    "prefecture": "東京都",
    "municipality": "港区",
    "address": "台場1丁目6番1号 DECKS Tokyo Beach 3F～5F",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "amusement"
    ],
    "price_text": "東京ジョイポリス入場料等が必要。ホロ×マッチ参加券は各回8,500円",
    "price_type": "paid",
    "is_free": false,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "東京ジョイポリス",
    "official_url": "https://tokyo-joypolis.com/event/hololive_jp2026/index.html",
    "category_keys": [
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "東京ジョイポリス",
    "source_url": "https://tokyo-joypolis.com/event/hololive_jp2026/index.html",
    "source_event_key": "hololive_jp2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "joypolis-hololive-shiny-party"
  },
  {
    "id": 92021,
    "slug": "qa-seed-joypolis-bloom-world",
    "title": "堂本光一 × ふぉ～ゆ～ BLOOM WORLD in JOYPOLIS",
    "summary": null,
    "start_date": "2026-07-09",
    "end_date": "2026-10-04",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "東京ジョイポリス",
    "postal_code": "135-0091",
    "prefecture": "東京都",
    "municipality": "港区",
    "address": "台場1丁目6番1号 DECKS Tokyo Beach 3F～5F",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "amusement"
    ],
    "price_text": "東京ジョイポリスの入場料・パスポート等が必要",
    "price_type": "paid",
    "is_free": false,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "東京ジョイポリス",
    "official_url": "https://tokyo-joypolis.com/event/kd_4u_jp/index.html",
    "category_keys": [
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "東京ジョイポリス",
    "source_url": "https://tokyo-joypolis.com/event/kd_4u_jp/index.html",
    "source_event_key": "kd_4u_jp",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "joypolis-bloom-world"
  },
  {
    "id": 92022,
    "slug": "qa-seed-tdc-space-travel-tour-2026",
    "title": "Space Travelium TeNQ 特別企画「体験型謎解き 宇宙トラベルツアー」",
    "summary": null,
    "start_date": "2026-10-22",
    "end_date": "2027-02-07",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "Space Travelium TeNQ 企画展示エリア",
    "postal_code": "112-8575",
    "prefecture": "東京都",
    "municipality": "文京区",
    "address": "後楽1-3-61",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "amusement"
    ],
    "price_text": "施設の入館料に含む",
    "price_type": "paid",
    "is_free": false,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "Space Travelium TeNQ",
    "official_url": "https://www.tokyo-dome.co.jp/tenq/event/exhibition-stt-8.html",
    "category_keys": [
      "learning",
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "東京ドームシティ",
    "source_url": "https://www.tokyo-dome.co.jp/tenq/event/exhibition-stt-8.html",
    "source_event_key": "exhibition-stt-8",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "tdc-space-travel-tour-2026"
  },
  {
    "id": 92023,
    "slug": "qa-seed-tdc-drstone-tenq-2026",
    "title": "TVアニメ「Dr.STONE」×Space Travelium TeNQ 企画展『ROAD TO THE MOON』",
    "summary": null,
    "start_date": "2026-07-18",
    "end_date": "2026-10-18",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "Space Travelium TeNQ 企画展示エリア",
    "postal_code": "112-8575",
    "prefecture": "東京都",
    "municipality": "文京区",
    "address": "後楽1-3-61",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "amusement"
    ],
    "price_text": "施設の入館料に含む",
    "price_type": "paid",
    "is_free": false,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "Space Travelium TeNQ",
    "official_url": "https://www.tokyo-dome.co.jp/tenq/event/exhibition-stt-7.html",
    "category_keys": [
      "learning",
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "東京ドームシティ",
    "source_url": "https://www.tokyo-dome.co.jp/tenq/event/exhibition-stt-7.html",
    "source_event_key": "exhibition-stt-7",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "tdc-drstone-tenq-2026"
  },
  {
    "id": 92024,
    "slug": "qa-seed-lalaport-pokemon-height-2026",
    "title": "さがして、はかって！ポケモンたかさ調査隊！",
    "summary": null,
    "start_date": "2026-09-18",
    "end_date": "2026-09-27",
    "start_time": "10:00",
    "end_time": "17:00",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "ららぽーとTOKYO-BAY 南館1F 南Bエスカレーター下 受付",
    "postal_code": "273-8530",
    "prefecture": "千葉県",
    "municipality": "船橋市",
    "address": "浜町2-1-1",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "mall"
    ],
    "price_text": "参加無料",
    "price_type": "free",
    "is_free": true,
    "reservation_required": false,
    "reservation_text": "各日先着1,000名・受付終了16:30",
    "organizer_name": null,
    "official_url": "https://mitsui-shopping-park.com/lalaport/tokyo-bay/event/3610874.html",
    "category_keys": [
      "family",
      "learning",
      "entertainment"
    ],
    "age_group_keys": [
      "preschool",
      "elementary",
      "family"
    ],
    "indoor": true,
    "audience_intent": "family_friendly",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "ららぽーとTOKYO-BAY",
    "source_url": "https://mitsui-shopping-park.com/lalaport/tokyo-bay/event/3610874.html",
    "source_event_key": "3610874",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "lalaport-pokemon-height-2026"
  },
  {
    "id": 92025,
    "slug": "qa-seed-lalaterrace-sanrio-wagon-2026",
    "title": "サンリオカフェワゴンがやってくる♪",
    "summary": null,
    "start_date": "2026-09-26",
    "end_date": "2026-09-27",
    "start_time": "10:00",
    "end_time": "18:00",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "ららテラスTOKYO-BAY エントランス周辺",
    "postal_code": null,
    "prefecture": "千葉県",
    "municipality": "船橋市",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "mall"
    ],
    "price_text": "商品購入は有料。イベント自体の入場料金記載なし",
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": null,
    "organizer_name": null,
    "official_url": "https://mitsui-shopping-park.com/lalaport/tokyo-bay/event/3637322.html",
    "category_keys": [
      "family",
      "food",
      "entertainment"
    ],
    "age_group_keys": [
      "family"
    ],
    "indoor": null,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "ららぽーとTOKYO-BAY",
    "source_url": "https://mitsui-shopping-park.com/lalaport/tokyo-bay/event/3637322.html",
    "source_event_key": "3637322",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "lalaterrace-sanrio-wagon-2026"
  },
  {
    "id": 92026,
    "slug": "qa-seed-lalaport-shinako-20260923",
    "title": "しなこちゃんイベント",
    "summary": null,
    "start_date": "2026-09-23",
    "end_date": "2026-09-23",
    "start_time": "13:00",
    "end_time": null,
    "all_day": false,
    "schedule_type": "single",
    "venue_name": "ららぽーとTOKYO-BAY North Gate 1F みどりの広場",
    "postal_code": "273-8530",
    "prefecture": "千葉県",
    "municipality": "船橋市",
    "address": "浜町2-1-1",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "mall"
    ],
    "price_text": "参加条件あり。GiGO対象プリ機での撮影と抽選が必要",
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": true,
    "reservation_text": "抽選当選者のみ参加（130組、1組2名まで）",
    "organizer_name": null,
    "official_url": "https://mitsui-shopping-park.com/lalaport/tokyo-bay/event/3611265.html",
    "category_keys": [
      "family",
      "entertainment"
    ],
    "age_group_keys": [
      "family"
    ],
    "indoor": null,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "ららぽーとTOKYO-BAY",
    "source_url": "https://mitsui-shopping-park.com/lalaport/tokyo-bay/event/3611265.html",
    "source_event_key": "3611265",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "lalaport-shinako-20260923"
  },
  {
    "id": 92027,
    "slug": "qa-seed-sakuratown-kozame-2026",
    "title": "おでかけ子ザメ おいSEA たのSEA サクラタウンさんぽ",
    "summary": null,
    "start_date": "2026-09-18",
    "end_date": "2026-11-08",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "ところざわサクラタウン（角川武蔵野ミュージアム、KadoCafeほか）",
    "postal_code": null,
    "prefecture": "埼玉県",
    "municipality": "所沢市",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "culture_public"
    ],
    "price_text": "一部有料",
    "price_type": "partly_free",
    "is_free": null,
    "reservation_required": null,
    "reservation_text": null,
    "organizer_name": "ところざわサクラタウン",
    "official_url": "https://tokorozawa-sakuratown.com/event_calendar/odekake-kozame.html",
    "category_keys": [
      "family",
      "entertainment"
    ],
    "age_group_keys": [
      "preschool",
      "elementary",
      "family"
    ],
    "indoor": null,
    "audience_intent": "family_friendly",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "ところざわサクラタウン",
    "source_url": "https://tokorozawa-sakuratown.com/event_calendar/odekake-kozame.html",
    "source_event_key": "odekake-kozame",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "sakuratown-kozame-2026"
  },
  {
    "id": 92028,
    "slug": "qa-seed-sakuratown-galaxy999-2026",
    "title": "『銀河鉄道999』50周年プロジェクト 松本零士展 創作の旅路",
    "summary": null,
    "start_date": "2026-09-19",
    "end_date": "2026-10-26",
    "start_time": "10:00",
    "end_time": "18:00",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "角川武蔵野ミュージアム 3階 展示室",
    "postal_code": null,
    "prefecture": "埼玉県",
    "municipality": "所沢市",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "culture_public"
    ],
    "price_text": "一般2,400円／中高生1,700円／小学生1,100円",
    "price_type": "paid",
    "is_free": false,
    "reservation_required": null,
    "reservation_text": "最終入場17:30",
    "organizer_name": "角川メディアハウス",
    "official_url": "https://tokorozawa-sakuratown.com/event_calendar/999-50thproject.html",
    "category_keys": [
      "art",
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "ところざわサクラタウン",
    "source_url": "https://tokorozawa-sakuratown.com/event_calendar/999-50thproject.html",
    "source_event_key": "999-50thproject",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "sakuratown-galaxy999-2026"
  },
  {
    "id": 92029,
    "slug": "qa-seed-sakuratown-essay-manga-2026",
    "title": "わたしをすくう エッセイマンガの処方箋展",
    "summary": null,
    "start_date": "2026-09-18",
    "end_date": "2027-01-11",
    "start_time": "10:00",
    "end_time": "18:00",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "角川武蔵野ミュージアム 4階 エディットアンドアートギャラリー",
    "postal_code": null,
    "prefecture": "埼玉県",
    "municipality": "所沢市",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "culture_public"
    ],
    "price_text": "一般1,400円／中高生1,200円／小学生1,000円／未就学児無料",
    "price_type": "partly_free",
    "is_free": null,
    "reservation_required": null,
    "reservation_text": "最終入館17:30",
    "organizer_name": "角川武蔵野ミュージアム",
    "official_url": "https://tokorozawa-sakuratown.com/event_categories/essay-manga.html",
    "category_keys": [
      "art",
      "learning"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "ところざわサクラタウン",
    "source_url": "https://tokorozawa-sakuratown.com/event_categories/essay-manga.html",
    "source_event_key": "essay-manga",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "sakuratown-essay-manga-2026"
  },
  {
    "id": 92030,
    "slug": "qa-seed-ariake-thanks-mama-mini-2026",
    "title": "Thanksママフォーラムmini",
    "summary": null,
    "start_date": "2026-09-22",
    "end_date": "2026-09-23",
    "start_time": "10:00",
    "end_time": "16:00",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "有明ガーデン モール内",
    "postal_code": null,
    "prefecture": "東京都",
    "municipality": "江東区",
    "address": "有明2-1-8",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "mall"
    ],
    "price_text": "参加無料（一部有料コンテンツあり）",
    "price_type": "partly_free",
    "is_free": null,
    "reservation_required": null,
    "reservation_text": "一部事前WEB予約制",
    "organizer_name": "住友不動産商業マネジメント株式会社",
    "official_url": "https://prtimes.jp/main/html/rd/p/000000497.000062100.html",
    "category_keys": [
      "family",
      "learning"
    ],
    "age_group_keys": [
      "age_0_2",
      "preschool",
      "family"
    ],
    "indoor": true,
    "audience_intent": "family_friendly",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "有明ガーデン",
    "source_url": "https://prtimes.jp/main/html/rd/p/000000497.000062100.html",
    "source_event_key": "thanks-mama-mini-20260922",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "ariake-thanks-mama-mini-2026"
  },
  {
    "id": 92031,
    "slug": "qa-seed-fujiko-15th-gadget-2026",
    "title": "藤子・F・不二雄ミュージアム開館15周年記念 ドラえも～ん！願いをかなえるひみつ道具展",
    "summary": null,
    "start_date": "2026-07-01",
    "end_date": "2027-06-20",
    "start_time": "10:00",
    "end_time": "18:00",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "川崎市 藤子・F・不二雄ミュージアム",
    "postal_code": "214-0023",
    "prefecture": "神奈川県",
    "municipality": "川崎市",
    "address": "多摩区長尾2丁目8番1号",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "culture_public",
      "event_venue_indoor"
    ],
    "price_text": "大人・大学生1,000円／高校・中学生700円／4歳以上500円／3歳以下無料。障がい者手帳所持者と介助者1名まで無料",
    "price_type": "partly_free",
    "is_free": null,
    "reservation_required": true,
    "reservation_text": "日時指定の事前予約制",
    "organizer_name": "川崎市 藤子・F・不二雄ミュージアム",
    "official_url": "https://fujiko-museum.com/info/topics/",
    "category_keys": [
      "learning",
      "art",
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [
      "disability_discount",
      "companion_support"
    ],
    "accessibility_notes": "障がい者手帳所持者は無料。障がい者1名につき介助者1名まで無料。",
    "fandom_slugs": [
      "doraemon"
    ],
    "source_name": "川崎市 藤子・F・不二雄ミュージアム",
    "source_url": "https://fujiko-museum.com/info/topics/",
    "source_event_key": "15th-gadget-exhibition-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "fujiko-15th-gadget-2026"
  },
  {
    "id": 92032,
    "slug": "qa-seed-kanagawa-life-satoyama-animals-2026",
    "title": "神奈川県立生命の星・地球博物館 特別展「しらべて分かった！里山にくらす動物たち」",
    "summary": null,
    "start_date": "2026-07-18",
    "end_date": "2026-11-08",
    "start_time": "09:00",
    "end_time": "16:30",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "神奈川県立生命の星・地球博物館 1階 特別展示室",
    "postal_code": "250-0031",
    "prefecture": "神奈川県",
    "municipality": "小田原市",
    "address": "入生田499",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "culture_public",
      "event_venue_indoor"
    ],
    "price_text": "20歳以上65歳未満720円／15歳以上20歳未満・学生400円／高校生・65歳以上200円／中学生以下無料",
    "price_type": "partly_free",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": null,
    "organizer_name": "神奈川県立生命の星・地球博物館",
    "official_url": "https://nh.kanagawa-museum.jp/exhibition/temporary/",
    "category_keys": [
      "learning",
      "nature"
    ],
    "age_group_keys": [
      "family"
    ],
    "indoor": true,
    "audience_intent": "family_friendly",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "神奈川県立生命の星・地球博物館",
    "source_url": "https://nh.kanagawa-museum.jp/exhibition/temporary/",
    "source_event_key": "special-satoyama-animals-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "kanagawa-life-satoyama-animals-2026"
  },
  {
    "id": 92033,
    "slug": "qa-seed-yokohama-english-garden-halloween-2026",
    "title": "横浜イングリッシュガーデン「ハロウィン・ディスプレイ2026」",
    "summary": null,
    "start_date": "2026-09-12",
    "end_date": "2026-10-31",
    "start_time": "10:00",
    "end_time": "18:00",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "横浜イングリッシュガーデン",
    "postal_code": "220-0024",
    "prefecture": "神奈川県",
    "municipality": "横浜市",
    "address": "西区西平沼町6-1 tvk ecom park内",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "park_plaza",
      "event_venue_outdoor"
    ],
    "price_text": "大人1,200円／小中学生600円／未就学児無料",
    "price_type": "partly_free",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": null,
    "organizer_name": "横浜イングリッシュガーデン",
    "official_url": "https://y-eg.jp/information/3905/",
    "category_keys": [
      "family",
      "nature",
      "entertainment"
    ],
    "age_group_keys": [
      "family"
    ],
    "indoor": false,
    "audience_intent": "family_friendly",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "横浜イングリッシュガーデン",
    "source_url": "https://y-eg.jp/information/3905/",
    "source_event_key": "halloween-display-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "yokohama-english-garden-halloween-2026"
  },
  {
    "id": 92034,
    "slug": "qa-seed-sankeien-moon-viewing-2026",
    "title": "横浜・三溪園「観月会」2026",
    "summary": null,
    "start_date": "2026-09-25",
    "end_date": "2026-09-29",
    "start_time": null,
    "end_time": "20:30",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "三溪園 内苑 臨春閣",
    "postal_code": "231-0824",
    "prefecture": "神奈川県",
    "municipality": "横浜市",
    "address": "中区本牧三之谷58-1",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "park_plaza",
      "event_venue_outdoor"
    ],
    "price_text": "演奏鑑賞無料（入園料別途）",
    "price_type": "partly_free",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": null,
    "organizer_name": "公益財団法人三溪園保勝会",
    "official_url": "https://www.sankeien.or.jp/event/10698/",
    "category_keys": [
      "art",
      "nature",
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": false,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "三溪園",
    "source_url": "https://www.sankeien.or.jp/event/10698/",
    "source_event_key": "moon-viewing-10698",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "sankeien-moon-viewing-2026"
  },
  {
    "id": 92035,
    "slug": "qa-seed-isumi-lobster-festival-2026",
    "title": "2026いすみイセエビまつり",
    "summary": null,
    "start_date": "2026-08-09",
    "end_date": "2026-10-25",
    "start_time": "08:00",
    "end_time": "12:30",
    "all_day": false,
    "schedule_type": "recurring",
    "venue_name": "大原漁港（港の朝市会場）",
    "postal_code": null,
    "prefecture": "千葉県",
    "municipality": "いすみ市",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "event_venue_outdoor"
    ],
    "price_text": "料金は各販売・企画の公式案内を確認",
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": null,
    "organizer_name": "港の朝市協同組合",
    "official_url": "https://isumi-kankou.com/iseebimaturi/",
    "category_keys": [
      "food",
      "market"
    ],
    "age_group_keys": [],
    "indoor": false,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "いすみ市観光センター",
    "source_url": "https://isumi-kankou.com/iseebimaturi/",
    "source_event_key": "iseebi-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "isumi-lobster-festival-2026"
  },
  {
    "id": 92036,
    "slug": "qa-seed-onjuku-lobster-festival-2026",
    "title": "おんじゅく伊勢えび祭り2026",
    "summary": null,
    "start_date": "2026-09-01",
    "end_date": "2026-10-31",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "月の沙漠記念館前広場・御宿町内協賛店",
    "postal_code": null,
    "prefecture": "千葉県",
    "municipality": "御宿町",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "park_plaza",
      "event_venue_outdoor"
    ],
    "price_text": "料理・直売・BBQ・各企画の料金は公式案内を確認",
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": null,
    "organizer_name": "御宿町観光協会",
    "official_url": "https://onjuku-kankou.com/event/iseebi/",
    "category_keys": [
      "food",
      "market"
    ],
    "age_group_keys": [],
    "indoor": false,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "御宿町観光協会",
    "source_url": "https://onjuku-kankou.com/event/iseebi/",
    "source_event_key": "iseebi-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "onjuku-lobster-festival-2026"
  },
  {
    "id": 92037,
    "slug": "qa-seed-sogo-suzuki-shintaro-2026",
    "title": "カラフルパレット 鈴木信太郎",
    "summary": null,
    "start_date": "2026-09-12",
    "end_date": "2026-10-12",
    "start_time": "10:00",
    "end_time": "20:00",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "そごう美術館（そごう横浜店 6階）",
    "postal_code": "220-8510",
    "prefecture": "神奈川県",
    "municipality": "横浜市",
    "address": "西区高島2-18-1",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "mall",
      "culture_public",
      "event_venue_indoor"
    ],
    "price_text": "一般1,200円／大学・高校生1,000円／中学生以下無料。障がい者手帳各種所持者と同伴者1名は無料",
    "price_type": "partly_free",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": "入館は閉館30分前まで。9月16日は19:00閉館",
    "organizer_name": "そごう美術館",
    "official_url": "https://www.sogo-seibu.jp/yokohama/topics/sogo-museum-suzuki-shintaro",
    "category_keys": [
      "art"
    ],
    "age_group_keys": [],
    "indoor": true,
    "audience_intent": "general",
    "accessibility_keys": [
      "disability_discount",
      "companion_support"
    ],
    "accessibility_notes": "障がい者手帳各種所持者と同伴者1名は入館無料。",
    "fandom_slugs": [],
    "source_name": "そごう横浜店・そごう美術館",
    "source_url": "https://www.sogo-seibu.jp/yokohama/topics/sogo-museum-suzuki-shintaro",
    "source_event_key": "sogo-museum-suzuki-shintaro-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "sogo-suzuki-shintaro-2026"
  },
  {
    "id": 92038,
    "slug": "qa-seed-solamachi-oktoberfest-2026",
    "title": "オクトーバーフェストin東京スカイツリータウン®2026",
    "summary": null,
    "start_date": "2026-09-19",
    "end_date": "2026-10-26",
    "start_time": "11:00",
    "end_time": "21:00",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "東京ソラマチ 4F スカイアリーナ",
    "postal_code": "131-0045",
    "prefecture": "東京都",
    "municipality": "墨田区",
    "address": "押上1-1-2",
    "location_precision": "exact_address",
    "location_verified": true,
    "venue_type_keys": [
      "mall",
      "event_venue_outdoor"
    ],
    "price_text": null,
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": "金・土および9月19日～23日は21:30まで。ラストオーダーは通常20:30、延長日は21:00",
    "organizer_name": null,
    "official_url": "https://www.tokyo-solamachi.jp/event/2811/",
    "category_keys": [
      "food",
      "festival"
    ],
    "age_group_keys": [],
    "indoor": false,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "東京ソラマチ",
    "source_url": "https://www.tokyo-solamachi.jp/event/2811/",
    "source_event_key": "event-2811",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "solamachi-oktoberfest-2026"
  },
  {
    "id": 92039,
    "slug": "qa-seed-sawara-autumn-festival-2026",
    "title": "佐原の大祭 秋祭り",
    "summary": null,
    "start_date": "2026-10-09",
    "end_date": "2026-10-11",
    "start_time": "10:00",
    "end_time": "22:00",
    "all_day": false,
    "schedule_type": "continuous",
    "venue_name": "香取市佐原 新宿地区・佐原信用金庫ステージ広場ほか",
    "postal_code": null,
    "prefecture": "千葉県",
    "municipality": "香取市",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "event_venue_outdoor"
    ],
    "price_text": null,
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": "雨天決行。山車運行・演目は日ごとの公式日程を確認",
    "organizer_name": "佐原の大祭実行委員会",
    "official_url": "https://www.city.katori.lg.jp/sightseeing/matsuri/introduction/aki.html",
    "category_keys": [
      "festival",
      "art"
    ],
    "age_group_keys": [],
    "indoor": false,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "香取市",
    "source_url": "https://www.city.katori.lg.jp/sightseeing/matsuri/introduction/aki.html",
    "source_event_key": "sawara-autumn-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "sawara-autumn-festival-2026"
  },
  {
    "id": 92040,
    "slug": "qa-seed-kawasaki-tamagawa-fireworks-2026",
    "title": "第85回 川崎市制記念多摩川花火大会",
    "summary": null,
    "start_date": "2026-10-03",
    "end_date": "2026-10-03",
    "start_time": "18:00",
    "end_time": "19:00",
    "all_day": false,
    "schedule_type": "single",
    "venue_name": "多摩川河川敷（二子橋～第三京浜道路間）",
    "postal_code": null,
    "prefecture": "神奈川県",
    "municipality": "川崎市",
    "address": null,
    "location_precision": "approximate",
    "location_verified": false,
    "venue_type_keys": [
      "event_venue_outdoor"
    ],
    "price_text": null,
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": "荒天中止",
    "organizer_name": "川崎市・一般社団法人川崎市観光協会・高津観光協会",
    "official_url": "https://www.city.kawasaki.jp/280/page/0000117559.html",
    "category_keys": [
      "fireworks",
      "festival"
    ],
    "age_group_keys": [],
    "indoor": false,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "川崎市",
    "source_url": "https://www.city.kawasaki.jp/280/page/0000117559.html",
    "source_event_key": "tamagawa-fireworks-85-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "kawasaki-tamagawa-fireworks-2026"
  },
  {
    "id": 92041,
    "slug": "qa-seed-kawasaki-port-festival-2026",
    "title": "川崎港開港75周年記念 第53回川崎みなと祭り",
    "summary": null,
    "start_date": "2026-10-10",
    "end_date": "2026-10-11",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "川崎マリエン周辺・東扇島東公園",
    "postal_code": null,
    "prefecture": "神奈川県",
    "municipality": "川崎市",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "park_plaza",
      "culture_public",
      "event_venue_outdoor"
    ],
    "price_text": null,
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": "雨天決行・荒天中止。各企画の時間や参加条件は公式サイトで確認",
    "organizer_name": "川崎市・川崎商工会議所・公益社団法人川崎港振興協会",
    "official_url": "https://kawasakiminato.com/",
    "category_keys": [
      "festival",
      "learning",
      "experience"
    ],
    "age_group_keys": [],
    "indoor": null,
    "audience_intent": "family_friendly",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "川崎みなと祭り実行委員会",
    "source_url": "https://kawasakiminato.com/",
    "source_event_key": "kawasaki-minato-53-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "kawasaki-port-festival-2026"
  },
  {
    "id": 92042,
    "slug": "qa-seed-seibuen-sidem-2026",
    "title": "アイドルマスター SideM 超!!レトローズパーティ",
    "summary": null,
    "start_date": "2026-10-30",
    "end_date": "2026-12-01",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "西武園ゆうえんち",
    "postal_code": null,
    "prefecture": "埼玉県",
    "municipality": "所沢市",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "amusement"
    ],
    "price_text": null,
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": "入園・個別企画・チケット条件は公式案内を確認",
    "organizer_name": "西武園ゆうえんち",
    "official_url": "https://www.seibuen-amusement-park.jp/event/index.html",
    "category_keys": [
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": null,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [
      "idolmaster-sidem"
    ],
    "source_name": "西武園ゆうえんち",
    "source_url": "https://www.seibuen-amusement-park.jp/event/index.html",
    "source_event_key": "sidem-super-retrose-party-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "seibuen-sidem-2026"
  },
  {
    "id": 92043,
    "slug": "qa-seed-seibuen-wanwan-halloween-2026",
    "title": "わんわん西武園ゆうえんち ～わんだふるハロウィン～",
    "summary": null,
    "start_date": "2026-10-23",
    "end_date": "2026-10-25",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "西武園ゆうえんち",
    "postal_code": null,
    "prefecture": "埼玉県",
    "municipality": "所沢市",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "amusement"
    ],
    "price_text": null,
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": "入園・愛犬同伴条件・個別企画は公式案内を確認",
    "organizer_name": "西武園ゆうえんち",
    "official_url": "https://www.seibuen-amusement-park.jp/event/index.html",
    "category_keys": [
      "entertainment"
    ],
    "age_group_keys": [],
    "indoor": null,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "西武園ゆうえんち",
    "source_url": "https://www.seibuen-amusement-park.jp/event/index.html",
    "source_event_key": "wanwan-halloween-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "seibuen-wanwan-halloween-2026"
  },
  {
    "id": 92044,
    "slug": "qa-seed-seibuen-parallel-toshimaen-2026",
    "title": "西武園ゆうえんち パラレルワールドとしまえん",
    "summary": null,
    "start_date": "2026-09-15",
    "end_date": "2026-10-25",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "西武園ゆうえんち",
    "postal_code": null,
    "prefecture": "埼玉県",
    "municipality": "所沢市",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "amusement"
    ],
    "price_text": null,
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": "展示・体験内容・入園条件は公式案内を確認",
    "organizer_name": "西武園ゆうえんち",
    "official_url": "https://www.seibuen-amusement-park.jp/",
    "category_keys": [
      "entertainment",
      "art"
    ],
    "age_group_keys": [],
    "indoor": null,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "西武園ゆうえんち",
    "source_url": "https://www.seibuen-amusement-park.jp/",
    "source_event_key": "parallel-toshimaen-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "seibuen-parallel-toshimaen-2026"
  },
  {
    "id": 92045,
    "slug": "qa-seed-chiba-raw-shake-festival-2026",
    "title": "第8回 千葉 生シェイク祭り2026",
    "summary": null,
    "start_date": "2026-06-01",
    "end_date": "2026-10-31",
    "start_time": null,
    "end_time": null,
    "all_day": true,
    "schedule_type": "continuous",
    "venue_name": "千葉県内参加店舗",
    "postal_code": null,
    "prefecture": "千葉県",
    "municipality": "複数",
    "address": null,
    "location_precision": "unknown",
    "location_verified": false,
    "venue_type_keys": [
      "other"
    ],
    "price_text": "参加店舗・商品により異なる",
    "price_type": "unknown",
    "is_free": null,
    "reservation_required": false,
    "reservation_text": "店舗ごとの提供期間・営業時間・商品情報は公式参加店舗一覧を確認",
    "organizer_name": "須藤牧場",
    "official_url": "https://www.sudo-farm.com/stamp-rally/stamp-book/list-boso?city=1",
    "category_keys": [
      "food"
    ],
    "age_group_keys": [],
    "indoor": null,
    "audience_intent": "general",
    "accessibility_keys": [],
    "accessibility_notes": null,
    "fandom_slugs": [],
    "source_name": "須藤牧場 生シェイク祭り",
    "source_url": "https://www.sudo-farm.com/stamp-rally/stamp-book/list-boso?city=1",
    "source_event_key": "raw-shake-festival-2026",
    "last_verified_at": "2026-09-28T00:00:00+09:00",
    "seed_slug": "chiba-raw-shake-festival-2026"
  }
] as const;
